version: '3.8'

volumes:
  umanz-pg-volume:
  pgadmin-data:

services:
  umanz-pg:
    image: postgres:15
    container_name: umanz-pg
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: umanz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itu16
    volumes:
      - umanz-pg-volume:/var/lib/postgresql/data
      - ./rhAPI/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d umanz" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: umanz-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umanz.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - umanz-pg

  mailhog:
    image: mailhog/mailhog
    container_name: umanz-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  rhapi-api:
    build: ./rhAPI
    container_name: umanz-rhapi
    ports:
      - "8443:8443"
    environment:
      spring.datasource.url: jdbc:postgresql://umanz-pg:5432/umanz
      spring.mail.host: umanz-mailhog
    depends_on:
      umanz-pg:
        condition: service_healthy

  umanz-app:
    build: ./umanz_app
    container_name: umanz-app
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_URL: https://localhost:8443
    depends_on:
      - rhapi-api
