spring.application.name=RHAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/rh
spring.datasource.username=db_user
spring.datasource.password=db_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,mappings

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080

# Configuration SMTP
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=neggadmin
# spring.mail.password=crgyvlhzmezpqdkc

# Propriétés avancées
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true
# spring.mail.properties.mail.smtp.connectiontimeout=5000
# spring.mail.properties.mail.smtp.timeout=5000
# spring.mail.properties.mail.smtp.writetimeout=5000

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# UmanZ
umanz.mfa.encryption.key=default.umanz.mfa.encryption.key