spring.application.name=RHAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/rh
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=mappings

server.port=8443
server.ssl.key-store=
server.ssl.key-store-password=
server.ssl.key-store-type=
server.ssl.key-alias=

# SMTP
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

# SMTP advanced
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
